import './globals.css'
import { Inter } from 'next/font/google'
import React from "react";
import Script from "next/script";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: '타요타요',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Script
          type={"text/javascript"}
          src={`https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=${process.env.NEXT_PUBLIC_NAVER_MAP_KEY}`}
      ></Script>
      {children}
      </body>

    </html>
  )
}
